import { z } from "zod";
import { interrupt } from "@langchain/langgraph";
import { event } from "./state";
import { structured } from "./llm";
import { ArticleSchema, CritiqueSchema, DraftSchema, PlanSchema, SummarySchema, type AgentState, type SearchResult } from "./types";
import { critiquePrompt, draftPrompt, planPrompt, revisionPrompt, selectionPrompt, summaryPrompt } from "./prompts";
import { dedupeSources, fetchArticle, renderNewsletter, searchNews } from "./tools";
import { env } from "@/lib/env";

const errors=(node:string, error:unknown)=>({errors:[{node,message:error instanceof Error?error.message:"Unknown error",recoverable:true}]});
export async function planNode(state:AgentState) { try { const plan=await structured(PlanSchema,planPrompt(state.goal)); return {plan,events:[event("plan","Planning","completed",`${plan.queries.length} search queries prepared; target ${plan.articleTarget} items.`)]}; } catch(e){return {...errors("plan",e),status:"failed" as const,events:[event("plan","Planning","warning","Planning failed.")]};} }
export async function searchNode(state:AgentState) { try { const queries=state.plan?.queries||["latest AI agent news","agentic AI announcements"]; const batches=await Promise.allSettled(queries.map(searchNews)); const found=batches.flatMap(r=>r.status==="fulfilled"?r.value:[]); const results=dedupeSources(found).filter(r=>Date.parse(r.publishedAt)>=Date.now()-14*86400000); return {searchResults:results,events:[event("search","News search","completed",`${results.length} unique sources discovered${state.retried?" after broader retry":""}.`)]}; } catch(e){return {...errors("search",e),status:"failed" as const,events:[event("search","News search","warning","Search provider failed.")]};} }
export async function selectNode(state:AgentState) { try { const candidates=state.searchResults.slice(0,30); const urls=await structured(z.array(z.string().url()).min(1).max(9),selectionPrompt(JSON.stringify(candidates))); const picked=urls.map(u=>candidates.find(c=>c.url===u)).filter(Boolean) as SearchResult[]; const selected=(picked.length?picked:candidates.slice(0,9)); return {selected,events:[event("select","Rank and select","completed",`${selected.length} sources selected for retrieval.`)]}; } catch(e){ const selected=state.searchResults.slice(0,9); return {...errors("select",e),selected,events:[event("select","Rank and select","warning",`Ranking degraded to deterministic recency order; ${selected.length} sources selected.`)]};} }
export async function collectNode(state:AgentState) { const collected=await Promise.all(state.selected.map(fetchArticle)); const usable=collected.filter(a=>a.content.length>=80); const degraded=usable.filter(a=>a.evidenceType==="snippet").length; return {articles:usable,events:[event("collect","Article fetching","completed",`${usable.length}/${state.selected.length} usable; ${degraded} snippet-only evidence.`)]}; }
export async function summarizeNode(state:AgentState) { try { const usable=state.articles.filter(a=>a.content.length>=80).slice(0,9); if(usable.length<5) return {summaries:[],events:[event("summarize","Summarization","warning",`Only ${usable.length} usable sources available.`)]}; const schema=z.array(SummarySchema).min(5).max(7); const summaries=await structured(schema,summaryPrompt(JSON.stringify(usable.map(a=>({...a,content:a.content.slice(0,6000)})))); return {summaries,events:[event("summarize","Summarization","completed",`${summaries.length} grounded article summaries created.`)]}; } catch(e){return {...errors("summarize",e),summaries:[],events:[event("summarize","Summarization","warning","Structured summary generation failed.")]};} }
export async function broadenNode(state:AgentState) { const plan={...(state.plan!),queries:["AI agents product launch research enterprise news", "autonomous agent AI industry news"],articleTarget:7}; return {plan,retried:true,events:[event("broaden","Broader research retry","completed","Fewer than five usable sources; running one broader query set.")]}; }
export async function draftNode(state:AgentState) { try { const draft=await structured(DraftSchema,draftPrompt(JSON.stringify(state.summaries))); return {draft,finalNewsletter:draft,events:[event("draft","Newsletter drafting","completed",`${draft.items.length} items drafted with subject line.`)]}; } catch(e){return {...errors("draft",e),status:"failed" as const,events:[event("draft","Newsletter drafting","warning","Drafting failed.")]};} }
export async function critiqueNode(state:AgentState) { try { const critique=await structured(CritiqueSchema,critiquePrompt(JSON.stringify(state.draft))); return {critique,events:[event("critique","Self-critique","completed",`Score ${critique.score}/100 - ${critique.decision.toUpperCase()}. ${critique.issues.length} issue(s) identified.`)]}; } catch(e){return {...errors("critique",e),critique:{score:100,decision:"pass",issues:["Critique unavailable; draft retained."],revisionInstructions:[]},events:[event("critique","Self-critique","warning","Critique failed; retaining grounded draft.")]};} }
export async function reviseNode(state:AgentState) { try { const finalNewsletter=await structured(DraftSchema,revisionPrompt(JSON.stringify(state.draft),JSON.stringify(state.critique))); return {finalNewsletter,revised:true,events:[event("revise","Revision","completed","One critique-driven revision applied.")]}; } catch(e){return {...errors("revise",e),finalNewsletter:state.draft,revised:true,events:[event("revise","Revision","warning","Revision failed; original draft retained.")]};} }
export function approvalNode(state:AgentState) { if(state.mode==="autonomous") return {events:[event("approval","Autonomous output","completed","Autonomous mode bypassed human approval.")]}; const decision=interrupt({runId:state.runId,newsletter:state.finalNewsletter,critique:state.critique,message:"Review the newsletter and approve or reject simulated sending."}) as {approved?:boolean}; if(!decision?.approved) return {status:"cancelled" as const,events:[event("approval","HITL approval","cancelled","Human reviewer rejected simulated sending.")]}; return {events:[event("approval","HITL approval","completed","Human reviewer approved simulated sending.")]}; }
export function sendNode(state:AgentState) { if(state.status==="cancelled") return {}; const newsletter=state.finalNewsletter!; const html=renderNewsletter(newsletter); return {html,status:"completed" as const,output:{status:"simulated_sent" as const,subject:newsletter.subject,recipientCount:env.recipients,sentAt:new Date().toISOString()},events:[event("send","Simulated send","completed",`Email simulated to ${env.recipients.toLocaleString()} subscribers.`)]}; }
